version: '3'
services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - oauth
      - elite2
      - offender-case-notes
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_ENDPOINT_URL=http://localhost:8080
      - OAUTH_ENDPOINT_URL=http://localhost:9090

  oauth:
    image: mojdigitalstudio/nomis-oauth2-server:latest
    container_name: oauth_nn
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  elite2:
    image: mojdigitalstudio/elite2-api:latest
    container_name: elite2_nn
    depends_on:
      - oauth
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  offender-case-notes:
    image: mojdigitalstudio/offender-case-notes:latest
    container_name: offender-case-notes
    depends_on:
      - offender-case-notes-db
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - ELITE2_API_BASE_URL=http://elite2-api:8080
      - OAUTH_API_BASE_URL=http://oauth:8080/auth
      - SPRING_PROFILES_ACTIVE=stdout

  redis:
    image: redis
    ports:
      - 6379:6379
