version: '3'
services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - oauth
      - elite2
      - offender-case-notes
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development

  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: oauth_nn
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  elite2:
    image: quay.io/hmpps/elite2-api:latest
    container_name: elite2_nn
    depends_on:
      - oauth
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  offender-case-notes:
    image: quay.io/hmpps/offender-case-notes:latest
    container_name: offender-case-notes_nn
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - ELITE2_API_BASE_URL=http://elite2:8080
      - OAUTH_API_BASE_URL=http://oauth:8080/auth
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://oauth:8080/auth/.well-known/jwks.json
      - SPRING_PROFILES_ACTIVE=dev,noqueue

  whereabouts:
    image: quay.io/hmpps/whereabouts-api:latest
    container_name: whereabouts_nn
    depends_on:
      - oauth
      - elite2
    ports:
      - '8082:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,noqueue
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://oauth:8080/auth/.well-known/jwks.json
      - OAUTH_ENDPOINT_URL=http://oauth:8080/auth
      - CASENOTES_ENDPOINT_URL=http://offender-case-notes:8080
      - ELITE2API_ENDPOINT_URL=http://elite2:8080

  keyworker-api:
    image: quay.io/hmpps/keyworker-api:latest
    depends_on:
      - elite2
      - oauth
    container_name: keyworker-api_nn
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - ELITE2_URI_ROOT=http://elite2:8080
      - AUTH_URI_ROOT=http://oauth:8080/auth
      - security.require-ssl=false
      - SPRING_PROFILES_ACTIVE=noqueue,local
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://oauth:8080/auth/.well-known/jwks.json

  redis:
    image: redis
    ports:
      - 6379:6379
