version: 2.1
parameters:
  image_name:
    type: string
    default: "quay.io/hmpps/new-nomis-ui"
  app_name:
    type: string
    default: "notm"

orbs:
  hmpps: ministryofjustice/hmpps@1.1.0

jobs:
  build:
    executor:
      name: hmpps/node
      tag: 12-buster-browsers
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: CYPRESS_INSTALL_BINARY=0 npm ci --no-audit
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run eslint
          command: npm run lint:js:ci
      - run:
          name: Run scss-lint
          command: npm run stylelint:ci
      - run:
          name: Run Tests
          command: |
            set -e
            npm test -- --maxWorkers=2
      - run: NODE_ENV=production npm run build
      - store_artifacts:
          path: test-report.html
      - store_artifacts:
          path: scss-report.txt
      - store_artifacts:
          path: eslint-report.html
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build

  integration_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:12-buster-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run the node app.
          command: npm run start-feature-no-webpack --env=feature.env
          background: true
      - run:
          name: Wait for node app to start
          command: sleep 10
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "notm-specs/build.gradle" }}
      - run:
          name: Run Integration Tests
          command: ./gradlew build --info
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "notm-specs/build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_artifacts:
          path: notm-specs/build/reports
          destination: integration/spock
      - store_artifacts:
          path: notm-specs/build/geb-reports
          destination: integration/geb
      - store_test_results:
          path: notm-specs/build/test-results

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - integration_tests:
          requires:
            - build
      - hmpps/helm_lint:
          name: helm_lint
          chart_name: "notm"
      - hmpps/build_docker:
          name: build_docker
          image_name: << pipeline.parameters.image_name >>
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          chart_name: "notm"
          release_name: "notm"
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
            - integration_tests
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          chart_name: "notm"
          release_name: "notm"
          name: deploy_preprod
          env: "preprod"
          context: notm-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          chart_name: "notm"
          release_name: "notm"
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context: notm-prod
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit
