# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: docker.io/mojdigitalstudio/new-nomis-ui
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: true
  host: digital-preprod.prison.service.justice.gov.uk
  cert_secret: notm-cert
  path: /

env:
  API_ENDPOINT_URL: "https://gateway.preprod.nomis-api.service.hmpps.dsd.io/elite2api/"
  OAUTH_ENDPOINT_URL: "https://gateway.preprod.nomis-api.service.hmpps.dsd.io/auth/"
  API_WHEREABOUTS_ENDPOINT_URL: "https://whereabouts-api-preprod.service.justice.gov.uk/"
  API_COMMUNITY_ENDPOINT_URL: "https://community-api-t2.hmpps.dsd.io/communityapi/"
  PRISON_STAFF_HUB_UI_URL: "https://whereabouts-preprod.prison.service.justice.gov.uk/"
  KEYWORKER_API_URL: "https://keyworker-api-preprod.prison.service.justice.gov.uk/"
  CASENOTES_API_URL: "https://preprod.offender-case-notes.service.justice.gov.uk"
  OMIC_UI_URL: "https://preprod.manage-key-workers.service.justice.gov.uk/"
  CATEGORISATION_UI_URL: "https://preprod.offender-categorisation.service.justice.gov.uk/"
  PATHFINDER_URL: "https://preprod.pathfinder.service.justice.gov.uk"
  MOIC_URL: "https://allocation-manager-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
  LICENCES_URL: "https://licences-preprod.prison.service.justice.gov.uk"
  USE_OF_FORCE_URL: "https://preprod.use-of-force.service.justice.gov.uk"
  ALLOCATION_MANAGER_ENDPOINT_URL: "https://allocation-manager-preprod.apps.live-1.cloud-platform.service.justice.gov.uk/"
  USE_OF_FORCE_PRISONS: "WRI,WEI,BLI"
  HMPPS_COOKIE_NAME: hmpps-session-preprod
  REMOTE_AUTH_STRATEGY: "true"
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"

whitelist:
  office: "217.33.148.210/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  health-kick: "35.177.252.195/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  mojvpn: "81.134.202.29/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  sodexo-northumberland: "88.98.48.10/32"
  thameside-private-prison: "217.22.14.151/32"
  ark-nps-hmcts-ttp1: "195.59.75.0/24"
  ark-nps-hmcts-ttp2: "194.33.192.0/25"
  ark-nps-hmcts-ttp3: "194.33.193.0/25"
  ark-nps-hmcts-ttp4: "194.33.196.0/25"
  ark-nps-hmcts-ttp5: "194.33.197.0/25"
  oakwood: "194.176.200.113/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  dxc_webproxy1: "195.92.38.20/32"
  dxc_webproxy2: "195.92.38.21/32"
  dxc_webproxy3: "195.92.38.22/32"
  dxc_webproxy4: "195.92.38.23/32"
